version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb_app
    restart: always
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker-app
      - MONGO_INITDB_ROOT_PASSWORD=123

volumes:
  database:
    driver: local

networks:
  app-network:
    driver: bridge
