version: '3'
services:
  next-app:
    build: ./
    container_name: next-auth-app
    env_file:
      - ./.env.local
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    depends_on:
      - mongo

  # Replica Set (required for Prisma Client)
  mongo:
    build: ./mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: mongo
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'
    restart: always # restart between reboots
    healthcheck:
      test: ['CMD', 'mongo', 'admin', '--port', '27018', '--eval', "db.adminCommand('ping')"]


volumes:
  database:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
