version: '3'
services:
  next-app:
    build: ./
    container_name: next-auth-app
    env_file:
      - ./.env.local
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb_app
    restart: always
    ports:
      - 27017:27017
    volumes:
      - database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker-app
      - MONGO_INITDB_ROOT_PASSWORD=123

volumes:
  database:
    driver: local

networks:
  app-network:
    driver: bridge
